I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 413, in script
    na "The doctor exits"
Exception: Sayer 'na' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 413, in script
    na "The doctor exits"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'na' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Dustborn 1.0
Thu Mar 17 14:15:07 2022
