I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 782, in script
    peacetech1 "No one expects the Peacetech Investigation!"
Exception: Sayer 'peacetech1' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 782, in script
    peacetech1 "No one expects the Peacetech Investigation!"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'peacetech1' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Dustborn 1.0
Sun Jul 31 12:56:50 2022
